---
title: "Tier 1 Cyber Assessment - Summary"
output: github_document
always_allow_html: true
---

```{r setup, include=FALSE}
library(readxl)
library(Rmisc)
library(Amelia)
library(Hmisc)
library(corrplot)
library(eRm)
library(ltm)
library(tidyverse)
library(psych)
library(kableExtra)
#####################Pre-process Script Begin
file <- "CyberCompetencies.xlsx"

#Scoring functions
likertNum <- function(x){
case_when(
        x == "Very Accurate" ~ 5, #Likert Scale 1 begin
        x == "Moderately Accurate" ~ 4,
        x == "Neither Accurate Nor Inaccurate" ~ 3,
        x == "Moderately Inaccurate" ~ 2,
        x == "Very Inaccurate" ~ 1,  #Likert Scale 1 end
        x == "Strongly Agree" ~ 5, #Likert Scale 2 begin
        x == "Moderately Agree" ~ 4,
        x == "Neither Agree nor Disagree" ~ 3,
        x == "Moderately Disagree" ~ 2,
        x == "Strongly Disagree" ~ 1 #Likert Scale 2 end
        )
}

#establish a threshold to discard respondent data based on missingness
miss_limit = .20 #percentage of missing data allowed

#count of missing items and standard deviation of responses: Personality
df_mis_P <-  read_xlsx(file) %>%
  gather(`1_ProblemSolver (Q1_A_1)`: `21_ToleranceOfAmbiguity (Q21_A_16)`, key=Question, value=Answer)  %>%
  group_by(`Record ID`) %>% 
  mutate_at(vars(Answer), likertNum) %>%  
  summarise(Miss_P = sum(is.na(Answer))/174)    #174 total Personality items
 
#count of missing items: Cognitive
df_mis_C <-  read_xlsx(file) %>% 
  gather(`Pattern_Q1 (Q23)`: `3D_Q16 (Q47)`, key=Question, value=Answer) %>%
  group_by(`Record ID`) %>%
  summarise(Miss_C = sum(is.na(Answer))/25, 
            sincere=sum(Answer=="I don't know", na.rm = TRUE)/25) #25 total Cognitive items

df_mis_C %>% mutate(Miss_C = Miss_C) %>% #visualization of missing items and count of "I don't know" answers
  select(-`Record ID`) %>% 
  rownames_to_column("ID") %>% 
  filter(Miss_C<miss_limit)  %>% 
  gather(Miss_C:sincere, key=Measure, value=Score) %>% 
  ggplot(aes(x=reorder(ID, Score, FUN=max), y=Score, color=Measure)) + 
  geom_point() +coord_flip() + facet_grid(.~Measure)

#load and pre-process raw data
df_preprocess <- read_xlsx(file) %>% 
        dplyr::rename(
        `Analogies_Q25 (Q34)` = `Analogies_Q16 (Q34)`, #fix mistake on label of question from ICAR; Analogies_Q25 used in test instead of Analogies_Q16
        `OSCP`        =`FormalCerts (Q58_1)`, #label certifications
        `OSCE`        = `FormalCerts (Q58_2)`,
        `GPEN`      = `FormalCerts (Q58_3)`,
        `GXPN`      = `FormalCerts (Q58_4)`,
        `GCIH`      = `FormalCerts (Q58_5)`,
        `CEH`       = `FormalCerts (Q58_6)`,
        `CISSP`     = `FormalCerts (Q58_7)`,
        `CISM`        = `FormalCerts (Q58_8)`,
        `Security+` = `FormalCerts (Q58_9)`,
        `OtherCert` = `FormalCerts (Q58_10)`) %>% 
        mutate(   `OSCP`      = if_else(OSCP =="OSCP", "Yes", "No"),
                  `OSCE`      = if_else(OSCE =="OSCE", "Yes", "No"),
                  `GPEN`      = if_else(GPEN =="GPEN", "Yes", "No"),
                  `GXPN`      = if_else(GXPN =="GXPN", "Yes", "No"),
                  `GCIH`      = if_else(GCIH =="GCIH", "Yes", "No"),
                  `CEH`       = if_else(CEH =="CEH", "Yes", "No"),
                  `CISSP`     = if_else(CISSP == "CISSP", "Yes", "No"),
                  `CISM`      = if_else(CISM == "CISM", "Yes", "No"), 
                  `Security+` = if_else(`Security+`=="Security+", "Yes", "No")) %>% 
        gather(`Rank (Q70)`:`Hexidecimal (Q69)`, key= "Question", value = "Response" ) %>% #cleaning demographic feature labels
        separate(col = `Question`, into=c("Question", "Question2"),  sep = " ", remove="TRUE") %>% 
        select (-Question2) %>% 
        pivot_wider(names_from = Question, values_from = Response) %>% 
        gather(`1_ProblemSolver (Q1_A_1)`: `21_ToleranceOfAmbiguity (Q21_A_16)`, key="Question", value = "Response") %>% #cleaning personality feature labels
        separate(col = `Question`, into=c("Question2", "Question"),  sep = "[(]", remove="TRUE") %>% 
        select(-Question2) %>% 
        separate(col = `Question`, into=c("Question", "Question2"),  sep = "[)]", remove="TRUE") %>% 
        select(-Question2)  %>% 
        pivot_wider(names_from = Question, values_from = Response) %>% 
        gather(`Pattern_Q1 (Q23)`:`3D_Q16 (Q47)`, key= "Question", value = "Response" ) %>%  #cleaning cognitive feature labels
        separate(col = `Question`, into=c("Question", "Question2"),  sep = " ", remove="TRUE") %>% 
        select(-Question2) %>% pivot_wider(names_from = Question, values_from = Response) %>%
        mutate(Duration_min = round((Completed - Started),2)) %>% #calculate questionnaire completion time
        mutate(Duration_min = replace_na(Duration_min, 0)) %>%  
        left_join(df_mis_P, by = "Record ID") %>% #join in missingness stat for Personality features
        left_join(df_mis_C, by = "Record ID") %>% #join in missingness stat and sincere stat for Cognitive features
        drop_na(Work_Role) %>% #drop rows with no data based on entry to work role
        arrange(Work_Role) %>% #arrange data by work role
        rownames_to_column("ID") %>% #add a new ID label beginning with 1
        select(-`Record ID`) %>% #remove Verint ID label
        select(ID,Miss_P, Miss_C, sincere, Duration_min, Rank:`3D_Q16`) #select features to carry forward in analysis

#Replace Work roles with simple categories
df_preprocess$Work_Role <-  gsub("Tier-1 - Remote Operator|Tier-1 - Capability Developer|Tier-1 - Exploitation Analyst", "Tier_1", df_preprocess$Work_Role)
df_preprocess$Work_Role <-  gsub("Tier 2- Data Architect, Network Analyst, System Analyst [(]All Master Proficiency level only[)]", "Tier_2", df_preprocess$Work_Role)
df_preprocess$Work_Role <-  gsub("Tier 3- Other work role directly assigned to a Cyber Mission Force Team", "Tier_3", df_preprocess$Work_Role)
df_preprocess$Work_Role <-  gsub("Tier 4 -  Other authorized cyber work role|I am currently not assigned a cyber work role or I am assigned as a student", "Tier_4", df_preprocess$Work_Role)
df_preprocess$Bachelors_CS <- replace_na(df_preprocess$Bachelors_CS, "No")
df_preprocess$Masters_CS <- replace_na(df_preprocess$Masters_CS, "No")
df_preprocess$Degree <- gsub("Bachelor's Degree [(]4 year[)]", "Bachelors", df_preprocess$Degree)
df_preprocess$Degree <- gsub("Master's Degree or higher", "Masters & Up", df_preprocess$Degree)
df_preprocess$Degree <- gsub("Some college or university but did not graduate", "Some College", df_preprocess$Degree)
df_preprocess$Degree <- gsub("High School Graduate", "High School", df_preprocess$Degree)
df_preprocess$Degree <- gsub("Associate Degree [(]2 year[)]", "Associates", df_preprocess$Degree)
df_preprocess$Experience <- gsub("6 years or more", ">5Years", df_preprocess$Experience)
df_preprocess$Experience <- gsub("5 years or less", "<=5Years", df_preprocess$Experience)
df_preprocess$Duration_min <- as.numeric(df_preprocess$Duration_min)


#####################Pre-process Script End
summary <- df_preprocess %>% 
   mutate(Complete = if_else(Duration_min >0, "Yes", "No")) %>% 
  summarySE(measurevar = "Duration_min", groupvars = c("Work_Role", "Complete" )) %>%
  select(Work_Role, Complete, N) %>% 
  pivot_wider(names_from = "Complete", values_from = "N") %>%  
  mutate(Yes=replace_na(Yes, 0)) %>% 
  dplyr::rename (Complete = `Yes`, Partial = `No`) %>% 
  mutate (Total = (Complete+Partial)) %>% 
  arrange(Work_Role)
```

## Missingness Map 

```{r missmap, echo=FALSE, message=FALSE, warning=FALSE}
#plot a missmap of raw data
missmap(df_preprocess %>% select(ID: `3D_Q16`, Duration_min) %>% arrange(Duration_min), rank.order=FALSE, main = "Missing values vs observed", legend = TRUE)
```

## Questionnaire Completion Totals

```{r completion_stats, echo=FALSE, message=FALSE, warning=FALSE}
summary %>% kable %>% kable_styling (bootstrap_options = c("striped", "hover", "condensed"), fixed_thead = T)
```

## Completion Duration (minutes)

```{r duration_plot, echo=FALSE, message=FALSE, warning=FALSE}
#plot of duation to complete
df_median <- df_preprocess %>% filter(Duration_min>0)
median <- median(df_median$Duration_min)
df_preprocess %>% filter(Duration_min>0) %>% ggplot() + geom_density(aes(x=Duration_min), fill="skyblue") +
        geom_vline(xintercept = median, linetype="dashed", color="red") + ylab("") +
        geom_text(aes(x=median, y=0), label=round(median,1)) +
        xlab("Questionnaire Duration (min)  *median labeled") + xlim(0,125)
```
